title: SciNetX
description: Public landing page and access request entry point
theme: jekyll-theme-cayman
show_downloads: false

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false
